# Traceroute Simulator Configuration File
# 
# This file contains default configuration options for the traceroute simulator.
# Command line arguments take precedence over these settings.
#
# Configuration file location precedence:
# 1. Environment variable TRACEROUTE_SIMULATOR_CONF (if set)
# 2. ~/traceroute_simulator.yaml (user's home directory)
# 3. ./traceroute_simulator.yaml (current directory - this file)
#
# Option value precedence (highest to lowest):
# 1. Command line arguments
# 2. Configuration file values
# 3. Hard-coded defaults

# Output configuration  
verbose: false                                  # Enable verbose output (-v flag)
verbose_level: 1                               # Verbosity level (1=basic, 2=detailed)
quiet: false                                   # Quiet mode (no output, exit codes only)
json_output: false                             # Output results in JSON format

# Tracing behavior
enable_mtr_fallback: true                      # Enable MTR fallback for incomplete paths
enable_reverse_trace: true                     # Enable reverse path tracing when forward fails

# Network discovery (required for reverse path tracing)
controller_ip: "127.0.0.1"                            # Ansible controller IP (required for reverse tracing)

# Registry files for network simulation state
registry_files:
  hosts: "/var/opt/traceroute-simulator/traceroute_hosts_registry.json"        # Host namespace registry
  routers: "/var/opt/traceroute-simulator/traceroute_routers_registry.json"    # Router/host name to code mappings
  interfaces: "/var/opt/traceroute-simulator/traceroute_interfaces_registry.json"  # Interface name to code mappings
  bridges: "/var/opt/traceroute-simulator/traceroute_bridges_registry.json"    # Bridge and connection registry
  services: "/var/opt/traceroute-simulator/traceroute_services_registry.json"  # Network services registry

