---
# Variables for ssh_restricted_access role - all values from config/default.yml

# User account variables
restricted_user_name: "{{ restricted_user.name }}"
restricted_user_comment: "{{ restricted_user.comment }}"
restricted_user_shell: "{{ restricted_user.shell }}"
restricted_user_home: "{{ restricted_user.home }}"
restricted_user_state: "{{ restricted_user.state }}"

# SSH configuration variables
ssh_restrict_option: "{{ ssh_config.restrict }}"
ssh_from_hosts: "{{ ssh_config.from_hosts }}"
ssh_pkey_file: "{{ ssh_config.pkey_file }}"
ssh_public_key: "{{ ssh_config.key_type }} {{ ssh_config.public_key }} {{ ssh_config.key_comment }}"
ssh_key_type: "{{ ssh_config.key_type }}"
ssh_key_comment: "{{ ssh_config.key_comment }}"

# Tracersh (wrapper script) variables
tracersh_enabled: "{{ tracersh.enabled }}"
tracersh_path: "{{ tracersh.path }}"
tracersh_preferred_tool: "{{ tracersh.preferred_tool }}"
tracersh_traceroute_path: "{{ tracersh.traceroute_path }}"
tracersh_mtr_path: "{{ tracersh.mtr_path }}"
tracersh_validation_enabled: "{{ tracersh.validation.enabled }}"
tracersh_validation_pattern: "{{ tracersh.validation.pattern }}"
tracersh_logging_enabled: "{{ tracersh.logging.enabled }}"
tracersh_logging_path: "{{ tracersh.logging.path }}"

# Security settings variables
security_home_dir_mode: "{{ security.home_dir_mode }}"
security_ssh_dir_mode: "{{ security.ssh_dir_mode }}"
security_authorized_keys_mode: "{{ security.authorized_keys_mode }}"
security_tracersh_mode: "{{ security.tracersh_mode }}"
security_log_file_mode: "{{ security.log_file_mode }}"
security_log_dir_mode: "{{ security.log_dir_mode }}"

# Backup variables
backup_enabled: "{{ backup.enabled }}"
backup_path: "{{ backup.path }}"

# Notification variables
notification_enabled: "{{ notification.enabled }}"
notification_email: "{{ notification.email }}"
notification_on_deploy: "{{ notification.on_deploy }}"
notification_on_remove: "{{ notification.on_remove }}"
notification_on_error: "{{ notification.on_error }}"
